name: Selenoid included tests

on:
  workflow_dispatch:
  push:
    branches: [ my_branch ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Pull project
      uses: actions/checkout@v3
    - name: Start selenoid
      uses: Xotabu4/selenoid-github-action@v2
    - name: Install python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' 

    - name: Setup different needs
      run: python -m pip install pytest-zebrunner && python -m pip install selenium && python -m pip install pytest
      
    - name: Run tests
      run: cd sample-pytest && python -m pytest -s -v tests/advanced_test.py
